services:
    robertheim.topictags.listener:
        class: robertheim\topictags\event\main_listener
        arguments:
            - '@config'
            - '@robertheim.topictags.tags_manager'
            - '@controller.helper'
            - '@request'
            - '@user'
            - '@template'
            - '@auth'
            - '@robertheim.topictags.tagcloud_manager'
        tags:
            - { name: event.listener }
    robertheim.topictags.acp_listener:
        class: robertheim\topictags\event\acp_listener
        arguments:
            - '@request'
            - '@user'
            - '@robertheim.topictags.tags_manager'
        tags:
            - { name: event.listener }
    robertheim.topictags.controller:
        class: robertheim\topictags\controller\main
        arguments:
            - '@config'
            - '@template'
            - '@controller.helper'
            - '@request'
            - '@user'
            - '@auth'
            - '@dispatcher'
            - '@pagination'
            - '@content.visibility'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '@robertheim.topictags.tags_manager'
            - '@robertheim.topictags.tagcloud_manager'
    robertheim.topictags.db_helper:
        class: robertheim\topictags\service\db_helper
        arguments:
            - '@dbal.conn.driver'
    robertheim.topictags.tags_manager:
        class: robertheim\topictags\service\tags_manager
        arguments:
            - '@dbal.conn.driver'
            - '@config'
            - '@config_text'
            - '@auth'
            - '@robertheim.topictags.db_helper'
            - '%core.table_prefix%'
    robertheim.topictags.tagcloud_manager:
        class: robertheim\topictags\service\tagcloud_manager
        arguments:
            - '@dbal.conn.driver'
            - '@config'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.table_prefix%'
    robertheim.topictags.acp.manage_tags_controller:
        class: robertheim\topictags\acp\manage_tags_controller
        arguments:
            - '@config'
            - '@request'
            - '@user'
            - '@template'
            - '@pagination'
            - '@robertheim.topictags.tags_manager'
    robertheim.topictags.acp.white_and_blacklist_controller:
        class: robertheim\topictags\acp\white_and_blacklist_controller
        arguments:
            - '@config'
            - '@config_text'
            - '@request'
            - '@user'
            - '@template'
            - '@robertheim.topictags.tags_manager'

