#!/bin/bash

# Load Data Share server name from cronjobs.ini file.
if test -f /usr/share/gforge/cronjobs/cronjobs.ini ; then
	source /usr/share/gforge/cronjobs/cronjobs.ini
fi

# Test setting of Data Share server name variable.
if [ "${datashare_server}" = "" ]; then
	# Data Share server name not loaded from cronjobs.ini file; exit.
	exit 1
fi

# Success.
exit 0
